name: Update telega-overlay

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  refresh-overlay:
    name: Refresh inputs
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ipvych'
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    # - name: Add nix-community cache
    #   uses: cachix/cachix-action@v10
    #   with:
    #     name: nix-community
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Update flake inputs
      run: |
        nix flake update --commit-lock-file || true
    - name: Update inputs
      run: |
        ./update
    - name: Push commit with updated inputs
      run: |
        git pull --rebase --autostash
        git push
